### ISSUE TITLE
yo vuejs时生成package.json失败

### ISSUE THREAD

**Issue by jcto** [BirdEggegg/generator-vue#2]
create package.json
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: EACCES, permission denied '/Users/chn/Desktop/cao1/vue_study/vueExample/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at write (/usr/local/lib/node_modules/generator-vuejs/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/commit.js:15:6)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/generator-vuejs/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/commit.js:42:7)

**Comment by birdgg** [comment]
sudo 试过么

**Comment by jcto** [comment]
OK了  我记住上次是用了sudo  这次再用sudo试试  可以了
