### ISSUE TITLE
yo vuejs又有了下面的错误

### ISSUE THREAD

**Issue by jcto** [BirdEggegg/generator-vue#3]
# 又出现了下面这种错误

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCP.onread (net.js:559:26)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-      gyp.js" "rebuild"
gyp ERR! cwd     /Users/chn/Desktop/cao1/vue_study/vue_project/node_modules/webpack/node_modules/watchpack/n ode_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.8
```

**Comment by birdgg** [comment]
npm 和 node 版本太低了吧
